function obj = layer_definition(name, layer_type, input_dim, num_units, wt_sigma)
   obj = struct('name', name, 'layer_type', layer_type, ...
                'input_dim', input_dim, 'num_units', num_units, ...
                'wt_sigma', wt_sigma);
end
